spring:
  application:
    name: oye
  profiles:
    active: local
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:placeholder}
  jpa:
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:placeholder}
            client-secret: ${KAKAO_CLIENT_SECRET:placeholder}
            redirect-uri: "https://yegam.today/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id